name: Go Build

on:
  push:
    branches:
      - main  # Set your branch name here

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'  # Set this to the Go version you are using
      id: go

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      env:
        GOOS: linux
        GOARCH: 386
      run: |
        go build -o myapp-linux-32bit main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp-linux-32bit
        path: ./myapp-linux-32bit
